name: energy-saving-automation
services:
  energy-monitor:
    source:
      image: node:18-alpine
    build:
      dockerfile: ./Dockerfile
    env:
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - TARGET_URL=${TARGET_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30m
      timeout: 10s
      retries: 3
    schedule:
      - cron: "0 */6 * * *"
        command: npm start