name: Deploy to Zeabur

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run basic checks
        run: |
          echo "Running basic syntax check..."
          node -c index.js
          node -c scraper.js
          echo "✅ Syntax check passed"
          
      - name: Install Zeabur CLI
        run: npm install -g zeabur
        
      - name: Deploy to Zeabur
        env:
          ZEABUR_TOKEN: ${{ secrets.ZEABUR_TOKEN }}
        run: |
          if [ -n "$ZEABUR_TOKEN" ]; then
            echo "Using token authentication"
            zeabur auth login --token $ZEABUR_TOKEN
          else
            echo "Using username/password authentication"
            zeabur auth login --username ${{ secrets.ZEABUR_USERNAME }} --password ${{ secrets.ZEABUR_PASSWORD }}
          fi
          zeabur deploy